stages:
  - test
  - build-develop
  - deploy-database
  - deploy-web

test:
  image: python:3.5.2
  stage: test
  cache:
    key: pip-cache
    paths: [ .pip-openid ]
  services:
  - mysql:5.7
  variables:
    MYSQL_ROOT_PASSWORD: "123456"
    MYSQL_DATABASE: openid
    
    DATABASE_HOST: mysql
    DATABASE_NAME: openid
    DATABASE_USER: root
    DATABASE_PASSWORD: "123456"
    DATABASE_PORT: 3306
  
  script:
  - pip --cache-dir=.pip-openid install -r requirements.txt
  - cd openid
  - python manage.py test superadmin
  only:
  - develop
  when: manual

build-develop:
  image: docker:stable
  
  stage: build-develop
  
  script:
    - docker login -u dangvv1995 -p $DOCKERHUB_PASSS
    - docker build -t foobar .
    - docker tag foobar $GUNICORN_OPENID_IMAGE:$CI_COMMIT_REF_NAME
    - docker push $GUNICORN_OPENID_IMAGE:$CI_COMMIT_REF_NAME
  only:
  - develop
  when: manual

  
deploy-database:
  image: dangvv1995/kubectl:1.14.1
  variables:
    KUBECONFIG: admin.conf
  before_script:
    - echo "$KUBE_CONFIG" > $KUBECONFIG
  stage: deploy-database
  script:
    - kubectl apply -f OpenID-mysql.yaml
  when: manual
  
deploy-web:
  image: dangvv1995/kubectl:1.14.1
  variables:
    KUBECONFIG: admin.conf
  before_script:
    - echo "$KUBE_CONFIG" > $KUBECONFIG
  stage: deploy-web
  script:
    - kubectl apply -f OpenID-web.yaml
  when: manual
