### Create openid-mysql service
apiVersion: v1
kind: Service
metadata:
  name: openid-mysql
  labels:
    app: openid
spec:
  ports:
    - port: 3306
  selector:
    app: openid
    tier: mysql
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: openid-mysql
  labels:
    app: openid
spec:
  selector:
    matchLabels:
      app: openid # has to match .spec.template.metadata.labels
      tier: mysql
  serviceName: "openid-mysql"
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        app: openid # has to match .spec.selector.matchLabels
        tier: mysql
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mysql
        image: mysql:5.7
        args:
          - "--ignore-db-dir=lost+found"
          - "--character-set-server=utf8mb4"
          - "--collation-server=utf8mb4_unicode_ci"
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: "123456"
          - name: MYSQL_DATABASE
            value: "openid"
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "rook-ceph-block"
      resources:
        requests:
          storage: 5Gi
