apiVersion: mysql.oracle.com/v1alpha1
kind: Cluster
metadata:
  name: openid-mysql
spec:
  members: 1
  rootPasswordSecret:
    name: mysql-root-user-secret
  
  volumeClaimTemplate:
    metadata:
      name: data
    spec:
      storageClassName: rook-ceph-block
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: 5Gi
  backupVolumeClaimTemplate:
    metadata:
      name: backup-data
    spec:
      storageClassName: rook-ceph-block
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: 5Gi
