---
kind: ConfigMap
apiVersion: v1
metadata:
  name: mysql-config
  namespace: my-namespace
data:
  my.cnf: |-
    [mysqld]
    default_authentication_plugin=mysql_native_password
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-root-user-secret
  namespace: my-namespace
data:
  password: MTIzNDU2Cg==

---
apiVersion: mysql.oracle.com/v1alpha1
kind: Cluster
metadata:
  name: openid-mysql
  namespace: my-namespace
spec:
  members: 2
  config:
    name: mysql-config
  rootPasswordSecret:
    name: mysql-root-user-secret
  
  volumeClaimTemplate:
    metadata:
      name: data
    spec:
      storageClassName: rook-ceph-block
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: 5Gi
          
  backupVolumeClaimTemplate:
    metadata:
      name: backup-data
    spec:
      storageClassName: rook-ceph-block
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: 5Gi
